version: 1.0.{build}

branches:
  except:
    - gh-pages

skip_tags: true

configuration: Release

build:
  parallel: true
  project: KuduRest.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  
artifacts:
  - path: src\bin\$(configuration)\KuduRest.dll
  - path: src\bin\$(configuration)\KuduRest.pdb
